### ISSUE TITLE
Where is the sln file of your code? 

### ISSUE THREAD

**Issue by onbigion13** [BestOwl/ShadowsocksUWP#1]
Hey，Dude，Where is the sln file of your code? I don't quitely know about Cmake. If I wanna see the whole    project, should I deploy C-make libraries?

**Comment by BestOwl** [comment]
Just open `CMakeLists.txt` with Visual Studio, it will automatically generate .sln file for you.

**Comment by BestOwl** [comment]
Visual Studio 2017 have built-in CMake support, so you don't need to deploy cmake libraries.
